### ISSUE TITLE
tmuxinator error on launch

### ISSUE THREAD

**Issue by NW-MLakin** [braxeatssnacks/.dotfiles#2]
I get this error every time I try to run tmuxinator, looks to be related to ruby:
```
❯ tmuxinator new layout
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- thor (LoadError)
        from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from /Users/mlakin/.dotfiles/tmux/tmuxinator/bin/tmuxinator:4:in `<main>'
```

```
❯ which ruby
/usr/bin/ruby

tmuxinator git/tags/v0.15.0
❯ ruby -v
ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
```

```
tmuxinator git/tags/v0.15.0
❯ pwd
/Users/mlakin/.dotfiles/tmux/tmuxinator

tmuxinator git/tags/v0.15.0
❯ git branch
* [1] (HEAD detached at 825efb0)
  [2] master
```

**Comment by braxeatssnacks** [comment]
We found that this is an issue with system `ruby` &mdash; one hacky, interim solution is to force link `brew` `ruby` over the system installation.

```
brew link ruby --force
```

This could have unintended consequences, and _should be done w/ care_. One longterm solution is to configure the deploy script to leverage `rbenv` or `rvm`, initializing that with a `tmuxinator` compatible version

**Comment by mmlakin** [comment]
Get rid of tmuxinator in favor of tmuxp!!!

**Comment by mmlakin** [comment]
It has been done!  Long live tmuxp!
